server:
  port: 7901
  
spring:
  application:
    name: microservice-consumer-movie


eureka:
  client:
    service-url:
      defaultZone: http://admin:zj123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}