server:
  port: 7903
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cloud1
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: microservice-provider-user
      
      
eureka:
  client:
    service-url:
      defaultZone: http://admin:zj123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
